version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  redis:
    container_name : redis
    image: redis:7
    ports:
      - "6379:6379"

  web:
    container_name: django
    build: .
    command: >
      sh -c "cd ./celerytst &&
            python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_NAME=mydb
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    container_name: celery1
    build: .
    working_dir: /app/celerytst
    command: celery -A celerytst worker --loglevel=info -Q queue1
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  celery2:
    container_name: celery2
    build:
      context: ./celeryworker
      dockerfile: Dockerfile
    working_dir: /app/celeryworker
    command: celery -A celerytask worker --loglevel=info -Q queue2
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
